require:
  - "rubocop-rspec"
  - "rubocop-rails"

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "config/environments/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "Gemfile"
    - "config/initializers/*"
    - "db/seeds.rb"
    - "db/migrate/*"
  Max: 100

Lint/UnusedBlockArgument:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: "indented"

Metrics/BlockLength:
  Exclude:
    - "Gemfile"
    - "Guardfile"
    - "lib/tasks/auto_annotate_models.rake"
    - "spec/**/*.rb"

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: "snake_case"

Rails:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/routing/*"
    - "spec/features/**/*"
    - "spec/system/**/*"

RSpec/ExampleLength:
  Exclude:
    - "spec/features/**/*"

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - "spec/features/**/*"

RSpec/NestedGroups:
  Max: 3

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: "always"

Style/MixinUsage:
  Exclude:
    - "bin/setup"
    - "bin/update"

Style/PercentLiteralDelimiters:
  Exclude:
    - "Guardfile"

Style/RegexpLiteral:
  Exclude:
    - "Guardfile"

Style/StringLiterals:
  EnforcedStyle: "double_quotes"
  Exclude:
    - "Guardfile"

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
